import { ShirtType } from "../types";

export const SHIRTS: ShirtType[] = [
  {
    id: "arg",
    name: "Argentina",
    category: "national",
    price: 30000,
    images: ["/arg-1.webp", "/arg-2.webp", "/arg-3.webp"],
  },
  {
    id: "deu",
    name: "Alemania",
    category: "national",
    price: 30000,
    images: ["/deu-1.webp", "/deu-2.webp", "/deu-3.webp"],
  },
  {
    id: "jpn",
    name: "Japón",
    category: "national",
    price: 30000,
    images: ["/jpn-1.webp", "/jpn-2.webp", "/jpn-3.webp"],
  },
  {
    id: "cfc",
    name: "Chelsea",
    category: "premier-league",
    price: 30000,
    images: ["//cfc-1.webp", "/cfc-2.webp", "/cfc-3.webp"],
  },
  {
    id: "mun",
    name: "Manchester United",
    category: "premier-league",
    price: 30000,
    images: ["/mun-1.webp", "/mun-2.webp", "/mun-3.webp"],
  },
  {
    id: "mac",
    name: "Manchester City",
    category: "premier-league",
    price: 30000,
    images: ["/mac-1.webp", "/mac-2.webp", "/mac-3.webp"],
  },
  {
    id: "ars",
    name: "Arsenal",
    category: "premier-league",
    price: 30000,
    images: ["/ars-1.webp", "/ars-2.webp", "/ars-3.webp"],
  },
  {
    id: "bay",
    name: "FC Bayern",
    category: "bundesliga",
    price: 30000,
    images: ["/bay-1.webp", "/bay-2.webp", "/bay-3.webp"],
  },
  {
    id: "bvb",
    name: "Borussia Dortmund",
    category: "bundesliga",
    price: 30000,
    images: ["/bvb-1.webp", "/bvb-2.webp", "/bvb-3.webp"],
  },
  {
    id: "wol",
    name: "Wolfsburg",
    category: "bundesliga",
    price: 30000,
    images: ["/wol-1.webp", "/wol-2.webp", "/wol-3.webp"],
  },
  {
    id: "int",
    name: "Inter",
    category: "serie-a",
    price: 30000,
    images: ["/int-1.webp", "/int-2.webp", "/int-3.webp"],
  },
  {
    id: "mil",
    name: "Milan",
    category: "serie-a",
    price: 30000,
    images: ["/mil-1.webp", "/mil-2.webp", "/mil-3.webp"],
  },
  {
    id: "juv",
    name: "Juventus",
    category: "serie-a",
    price: 30000,
    images: ["/juv-1.webp", "/juv-2.webp", "/juv-3.webp"],
  },
  {
    id: "laz",
    name: "Lazio",
    category: "serie-a",
    price: 30000,
    images: ["/laz-1.webp", "/laz-2.webp", "/laz-3.webp"],
  },
  {
    id: "rom",
    name: "Roma",
    category: "serie-a",
    price: 30000,
    images: ["/rom-1.webp", "/rom-2.webp", "/rom-3.webp"],
  },
  {
    id: "atc",
    name: "Atlético Madrid",
    category: "la-liga",
    price: 30000,
    images: ["/atc-1.webp", "/atc-2.webp", "/atc-3.webp"],
  },
  {
    id: "bar",
    name: "Barcelona",
    category: "la-liga",
    price: 30000,
    images: ["/bar-1.webp", "/bar-2.webp", "/bar-3.webp"],
  },
  {
    id: "bet",
    name: "Real Betis",
    category: "la-liga",
    price: 30000,
    images: ["/bet-1.webp", "/bet-2.webp", "/bet-3.webp"],
  },
  {
    id: "rma",
    name: "Real Madrid",
    category: "la-liga",
    price: 30000,
    images: ["/rma-1.webp", "/rma-2.webp", "/rma-3.webp"],
  },
  {
    id: "sev",
    name: "Sevilla",
    category: "la-liga",
    price: 30000,
    images: ["/sev-1.webp", "/sev-2.webp", "/sev-3.webp"],
  },
];
